In [1]:
from joblib import dump, load

In [2]:
vectorizer = load('./model/vectorizer.joblib')
tfidf_transformer = load('./model/tfidf.joblib')
svm = load('./model/svm_linear.joblib')

In [3]:
new_test_counts = vectorizer.transform(["It's not true how often you need to stretch. 3 sets of 30 seconds three times a week per stretch is the IDEAL amount. That is very manageable.", 'So much false information in this video that I lost faith in ted ed.'])
new_test_tfidf = tfidf_transformer.transform(new_test_counts)
new_test_tfidf

<2x121925 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [4]:
svm.predict(new_test_tfidf)

array([1, 0], dtype=int64)

In [ ]:
svm.predict_pro

In [4]:
mnb = load('./model/multinomial_nb.joblib')

In [21]:
preds = mnb.predict(new_test_tfidf)
preds

array([1, 1], dtype=int64)

In [20]:
pred_probs = mnb.predict_proba(new_test_tfidf)
pred_probs

array([[0.29523284, 0.70476716],
       [0.23200666, 0.76799334]])

In [10]:
for i, prob in enumerate(pred_probs):
    if prob[preds[i]] < 80:
        preds[i] = 1 - preds[i]

In [25]:
for i, pred in enumerate(preds):
        if(pred == 1 and pred_probs[i][pred] < 0.70):
            print(pred_probs[i][pred])

In [19]:
preds

array([0, 0], dtype=int64)